# Infos Build
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@


# Server
server:
  address:  127.0.0.1
  port: 8080
  max-http-header-size: 16380
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain



